### ISSUE TITLE
Add demo questions

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#16]
Similar to ChatGPT add example questions

**Comment by XinlingWang0628** [comment]
Found a gradio parameter to add examples. Click example button will autofill the input box. But examples are below chatbot, instead of inside it. Is this okay, or you want exact same as GPT?

<img width="1255" alt="Screenshot 2024-07-10 at 2 54 27 PM" src="https://github.com/cannin/gsoc_2024_cbioportal_chatbot/assets/105673895/bd9ea79b-b8e1-4181-8929-f9448322cdb1">
